export const themeVariables = {
  spacing: {
    px: "var(--plusui-spacing-px, 0.0625rem)",
    0: "var(--plusui-spacing-0, 0rem)",
    0.5: "var(--plusui-spacing-0-5, 0.125rem)",
    0.75: "var(--plusui-spacing-0-75, 0.1875rem)",
    1: "var(--plusui-spacing-1, 0.25rem)", 
    1.5: "var(--plusui-spacing-1-5, 0.375rem)", 
    2: "var(--plusui-spacing-2, 0.5rem)",
    2.5: "var(--plusui-spacing-2-5, 0.625rem)",
    3: "var(--plusui-spacing-3, 0.75rem)",
    3.5: "var(--plusui-spacing-3-5, 0.875rem)",
    4: "var(--plusui-spacing-4, 16px)",
    4.5: "var(--plusui-spacing-4-5, 18px)",
    5: "var(--plusui-spacing-5, 20px)",
    5.5: "var(--plusui-spacing-5-5, 22px)",
    6: "var(--plusui-spacing-6, 24px)", 
    7: "var(--plusui-spacing-7, 28px)",
    8: "var(--plusui-spacing-8, 2rem)",
    9: "var(--plusui-spacing-9, 2.25rem)",
    10: "var(--plusui-spacing-10, 2.5rem)",
    11: "var(--plusui-spacing-11, 2.75rem)",
    12: "var(--plusui-spacing-12, 3rem)",
    14: "var(--plusui-spacing-14, 3.5rem)",
    16: "var(--plusui-spacing-16, 4rem)",
    20: "var(--plusui-spacing-20, 5rem)",
    24: "var(--plusui-spacing-24, 6rem)",
    28: "var(--plusui-spacing-28, 7rem)",
    32: "var(--plusui-spacing-32, 8rem)",
    36: "var(--plusui-spacing-36, 9rem)",
    40: "var(--plusui-spacing-40, 10rem)",
    44: "var(--plusui-spacing-44, 11rem)",
    48: "var(--plusui-spacing-48, 12rem)",
    52: "var(--plusui-spacing-52, 13rem)",
    56: "var(--plusui-spacing-56, 14rem)",
    60: "var(--plusui-spacing-60, 15rem)",
    64: "var(--plusui-spacing-64, 16rem)",
    72: "var(--plusui-spacing-72, 18rem)",
    80: "var(--plusui-spacing-80, 20rem)",
    96: "var(--plusui-spacing-96, 24rem)",
  },

  /* fontSize */
  fontSize: {
    "xs": ["var(--plusui-font-size-xs, 0.75rem)", { lineHeight: "var(--plusui-font-size-xs-line-height, 1rem)" }],
    "sm": ["var(--plusui-font-size-sm, 0.875rem)", { lineHeight: "var(--plusui-font-size-sm-line-height, 1.25rem)" }],
    "base": ["var(--plusui-font-size-base, 1rem)", { lineHeight: "var(--plusui-font-size-base-line-height, 1.5rem)" }],
    "lg": ["var(--plusui-font-size-lg, 1.125rem)", { lineHeight: "var(--plusui-font-size-lg-line-height, 1.75rem)" }],
    "xl": ["var(--plusui-font-size-xl, 1.25rem)", { lineHeight: "var(--plusui-font-size-xl-line-height, 1.75rem)" }],
    "2xl": ["var(--plusui-font-size-2xl, 1.5rem)", { lineHeight: "var(--plusui-font-size-2xl-line-height, 2rem)" }],
    "3xl": ["var(--plusui-font-size-3xl, 1.875rem)", { lineHeight: "var(--plusui-font-size-3xl-line-height, 2.25rem)" }],
    "4xl": ["var(--plusui-font-size-4xl, 2.25rem)", { lineHeight: "var(--plusui-font-size-4xl-line-height, 2.5rem)" }],
    "5xl": ["var(--plusui-font-size-5xl, 3rem)", { lineHeight: "var(--plusui-font-size-5xl-line-height, 1)" }],
    "6xl": ["var(--plusui-font-size-6xl, 3.75rem)", { lineHeight: "var(--plusui-font-size-6xl-line-height, 1)" }],
    "7xl": ["var(--plusui-font-size-7xl, 4.5rem)", { lineHeight: "var(--plusui-font-size-7xl-line-height, 1)" }],
    "8xl": ["var(--plusui-font-size-8xl, 6rem)", { lineHeight: "var(--plusui-font-size-8xl-line-height, 1)" }],
    "9xl": ["var(--plusui-font-size-9xl, 8rem)", { lineHeight: "var(--plusui-font-size-9xl-line-height, 1)" }],
    "size-inherit": ["inherit", { lineHeight: "inherit" }],
  },

  borderRadius: {
    none: "var(--plusui-border-radius-none, 0px)",
    sm: "var(--plusui-border-radius-sm, 0.125rem)",
    DEFAULT: "var(--plusui-border-radius-default, 0.25rem)",
    md: "var(--plusui-border-radius-md, 0.375rem)",
    lg: "var(--plusui-border-radius-lg, 0.5rem)",
    xl: "var(--plusui-border-radius-xl, 0.75rem)",
    "2xl": "var(--plusui-border-radius-2xl, 1rem)",
    "3xl": "var(--plusui-border-radius-3xl, 1.5rem)",
    full: "var(--plusui-border-radius-full, 9999px)",
  },

  opacity: {
    0: "var(--plusui-opacity-0, 0)",
    5: "var(--plusui-opacity-5, 0.05)",
    10: "var(--plusui-opacity-10, 0.1)",
    15: "var(--plusui-opacity-15, 0.15)",
    20: "var(--plusui-opacity-20, 0.2)",
    25: "var(--plusui-opacity-25, 0.25)",
    30: "var(--plusui-opacity-30, 0.3)",
    35: "var(--plusui-opacity-35, 0.35)",
    40: "var(--plusui-opacity-40, 0.4)",
    45: "var(--plusui-opacity-45, 0.45)",
    50: "var(--plusui-opacity-50, 0.5)",
    55: "var(--plusui-opacity-55, 0.55)",
    60: "var(--plusui-opacity-60, 0.6)",
    65: "var(--plusui-opacity-65, 0.65)",
    70: "var(--plusui-opacity-70, 0.7)",
    75: "var(--plusui-opacity-75, 0.75)",
    80: "var(--plusui-opacity-80, 0.8)",
    85: "var(--plusui-opacity-85, 0.85)",
    90: "var(--plusui-opacity-90, 0.9)",
    95: "var(--plusui-opacity-95, 0.95)",
    100: "var(--plusui-opacity-100, 1)",
  },
};

export const themeColors = {
  border: {
    primary: "var(--plusui-color-border-primary)",
    focus: "var(--plusui-color-border-focus)",
    disabled: "var(--plusui-color-border-disabled)",
    error: "var(--plusui-color-border-error)",
    success: "var(--plusui-color-border-success)",
    warning: "var(--plusui-color-border-warning)",
    default: "var(--plusui-color-border-default)",
    info: "var(--plusui-color-border-info)",
  },
  text: {
    base: "var(--plusui-color-text-base)",
    default: "var(--plusui-color-text-default)",
    primary: "var(--plusui-color-text-primary)",
    placeholder: "var(--plusui-color-text-placeholder)",
    link: "var(--plusui-color-text-link)",
    caption: "var(--plusui-color-text-caption)",
    visited: "var(--plusui-color-text-visited)",
    disabled: "var(--plusui-color-text-disabled)",
    error: "var(--plusui-color-text-error)",
    success: "var(--plusui-color-text-success)",
    warning: "var(--plusui-color-text-warning)",
    info: "var(--plusui-color-text-info)",
  },
  textInvert: {
    base: "var(--plusui-color-text-invert-base)",
    default: "var(--plusui-color-text-invert-default)",
    primary: "var(--plusui-color-text-invert-primary)",
    placeholder: "var(--plusui-color-text-invert-placeholder)",
    link: "var(--plusui-color-text-invert-link)",
    caption: "var(--plusui-color-text-invert-caption)",
    visited: "var(--plusui-color-text-invert-visited)",
    disabled: "var(--plusui-color-text-invert-disabled)",
    error: "var(--plusui-color-text-invert-error)",
    success: "var(--plusui-color-text-invert-success)",
    warning: "var(--plusui-color-text-invert-warning)",
    info: "var(--plusui-color-text-invert-info)",
  },
  background: {
    default: {
      DEFAULT: "var(--plusui-color-background-default-default)",
      hover: "var(--plusui-color-background-default-hover)",
      pressed: "var(--plusui-color-background-default-pressed)",
      focus: "var(--plusui-color-background-default-focus)",
    },
    disabled: "var(--plusui-color-background-disabled)",
    primary: {
      DEFAULT: "var(--plusui-color-background-primary-default)",
      hover: "var(--plusui-color-background-primary-hover)",
      pressed: "var(--plusui-color-background-primary-pressed)",
      focus: "var(--plusui-color-background-primary-focus)",
    },
    base: {
      DEFAULT: "var(--plusui-color-background-base-default)",
      hover: "var(--plusui-color-background-base-hover)",
      pressed: "var(--plusui-color-background-base-pressed)",
      focus: "var(--plusui-color-background-base-focus)",
    },
    success: {
      DEFAULT: "var(--plusui-color-background-success-default)",
      hover: "var(--plusui-color-background-success-hover)",
      pressed: "var(--plusui-color-background-success-pressed)",
      focus: "var(--plusui-color-background-success-focus)",
    },
    warning: {
      DEFAULT: "var(--plusui-color-background-warning-default)",
      hover: "var(--plusui-color-background-warning-hover)",
      pressed: "var(--plusui-color-background-warning-pressed)",
      focus: "var(--plusui-color-background-warning-focus)",
    },
    error: {
      DEFAULT: "var(--plusui-color-background-error-default)",
      hover: "var(--plusui-color-background-error-hover)",
      pressed: "var(--plusui-color-background-error-pressed)",
      focus: "var(--plusui-color-background-error-focus)",
    },
    info: {
      DEFAULT: "var(--plusui-color-background-info-default)",
      hover: "var(--plusui-color-background-info-hover)",
      pressed: "var(--plusui-color-background-info-pressed)",
      focus: "var(--plusui-color-background-info-focus)",
    },
  },
  backgroundInvert: {
    default: {
      DEFAULT: "var(--plusui-color-background-default-invert-default)",
      hover: "var(--plusui-color-background-default-invert-hover)",
      pressed: "var(--plusui-color-background-default-invert-pressed)",
      focus: "var(--plusui-color-background-default-invert-focus)",
    },
    primary: {
      DEFAULT: "var(--plusui-color-background-primary-invert-default)",
      hover: "var(--plusui-color-background-primary-invert-hover)",
      pressed: "var(--plusui-color-background-primary-invert-pressed)",
      focus: "var(--plusui-color-background-primary-invert-focus)",
    },
    success: {
      DEFAULT: "var(--plusui-color-background-success-invert-default)",
      hover: "var(--plusui-color-background-success-invert-hover)",
      pressed: "var(--plusui-color-background-success-invert-pressed)",
      focus: "var(--plusui-color-background-success-invert-focus)",
    },
    warning: {
      DEFAULT: "var(--plusui-color-background-warning-invert-default)",
      hover: "var(--plusui-color-background-warning-invert-hover)",
      pressed: "var(--plusui-color-background-warning-invert-pressed)",
      focus: "var(--plusui-color-background-warning-invert-focus)",
    },
    error: {
      DEFAULT: "var(--plusui-color-background-error-invert-default)",
      hover: "var(--plusui-color-background-error-invert-hover)",
      pressed: "var(--plusui-color-background-error-invert-pressed)",
      focus: "var(--plusui-color-background-error-invert-focus)",
    },
    info: {
      DEFAULT: "var(--plusui-color-background-info-invert-default)",
      hover: "var(--plusui-color-background-info-invert-hover)",
      pressed: "var(--plusui-color-background-info-invert-pressed)",
      focus: "var(--plusui-color-background-info-invert-focus)",
    },
  },
  surface: {
    base: "var(--plusui-color-surface-base)",
  },
};
